# define the project structure and workflow steps, based on this the folder structure will be created

project_name: "003_example_repair__public"
project_description: "This is a test project to test the workflow"

buildings: #Either add the building names / folder names manually here or use the create_buildings_from_files function 

building_folder:
  - "00_original_input_data"
  - "01_abstractbim_model"








