project_name: "003_test_project__public"

steps:
  - script: "run_collect_data.py"
    folder: "00_original_input_data"
  - script: "run_create_abstractBIM.py"
    folder: "01_abstractbim_model"
  - script: "run_assign_spatial_data.py"
    folder: "02_enriched_spatial_ifc"
  - script: "run_enrich_ifc_with_metadata.py"
    folder: "03_enriched_ifc"
  - script: "run_calculate_metrics.py"
    folder: "04_metrics_data"
  - script: "run_create_json_geometry.py"
    folder: "05_geometry_json"
  - script: "run_create_all_plots.py"
    folder: "06_visualizations"
  - script: "run_create_pdf_report.py"
    folder: "07_pdf_report"


buildings:
  - "test_building_001" 
  - "test_building_002" 


