from dataclasses import dataclass
from typing import Optional, Dict, Any

@dataclass
class ExcelLayoutConfig:
    """Configuration for Excel export layout."""
    horizontal_lines: bool = True
    vertical_lines: bool = False
    bold_headers: bool = True
    auto_column_width: bool = True
    row_height: Optional[float] = None
    alternating_colors: bool = False
    number_format: str = '#,##0.00'
    header_color: str = 'E0E0E0'  # Light gray
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert config to dictionary."""
        return {k: v for k, v in self.__dict__.items()}

@dataclass
class ReportStyleConfig:
    """Configuration for report styling."""
    logo_path: Optional[str] = None
    footer_text: str = "Generated by QTO Buccaneer"
    page_size: str = "A4"
    margin_top: str = "1.5cm"
    margin_bottom: str = "1.5cm"
    margin_left: str = "2cm"
    margin_right: str = "1.5cm"
    font_family: str = "Arial"
    font_size: str = "10pt"
    header_height: str = "2cm"
    footer_height: str = "2cm"
    
    def to_css(self) -> str:
        """Convert config to CSS string."""
        return f"""
            @page {{
                size: {self.page_size};
                margin-top: {self.margin_top};
                margin-bottom: {self.margin_bottom};
                margin-left: {self.margin_left};
                margin-right: {self.margin_right};
                
                @top-center {{
                    content: string(title);
                    font-family: {self.font_family};
                    font-size: {self.font_size};
                }}
                
                @bottom-left {{
                    content: string(project-name);
                    font-family: {self.font_family};
                    font-size: {self.font_size};
                }}
                
                @bottom-right {{
                    content: "Page " counter(page) " of " counter(pages);
                    font-family: {self.font_family};
                    font-size: {self.font_size};
                }}
            }}
            
            body {{
                font-family: {self.font_family};
                font-size: {self.font_size};
                margin: 0;  /* Reset body margin to ensure page margins are used */
            }}
            
            .header {{
                height: {self.header_height};
            }}
            
            .footer {{
                height: {self.footer_height};
                display: flex;
                justify-content: space-between;
                align-items: center;
                padding: 0 1em;
            }}
            
            .footer-left {{
                font-weight: bold;
            }}
            
            .logo {{
                max-height: 2cm;
                max-width: 5cm;
            }}
            
            string(project-name) {{
                content: "{self.footer_text}";
            }}
        """ 