plot_settings:
  # General plot settings
  title_font:
    family: "Arial"
    size: 24
    color: "black"
  
  # Space visualization settings
  space:
    line:
      color: "black"
      width: 2
    text:
      font:
        family: "Arial"
        size: 12
        color: "black"
    hover_template: "<b>%{customdata[0]}</b><br>Area: %{customdata[1]:.2f} m²"
  
  # Layout settings
  layout:
    showlegend: true
    legend:
      title:
        text: "Space Types"
      font:
        family: "Arial"
        size: 12
    margin:
      l: 50
      r: 50
      t: 50
      b: 50
    paper_bgcolor: "white"
    plot_bgcolor: "white"
    xaxis:
      title: "X [m]"
      showgrid: true
      gridcolor: "lightgray"
    yaxis:
      title: "Y [m]"
      showgrid: true
      gridcolor: "lightgray"
      scaleanchor: "x"
      scaleratio: 1 