# Configuration for project metrics.

# Each metric is defined as a dictionary with the following keys:
# - description: A short description of the metric.
# - quantity_type: The type of quantity to calculate. Options include:
#     - "area"
#     - "volume"
#     - "count"
# - ifc_entity: The IFC entity to calculate the quantity for (e.g. IfcWall, IfcSlab).
# - pset_name: The name of the Property Set (Pset) to retrieve the property from.
# - prop_name: The name of the property or attribute within the Pset (Property Set) to use for quantity calculation.
# - include_filter: A dictionary of conditions to include only specific elements.
# - include_filter_logic: Logical operator to combine multiple include filters. Options:
#     - "AND"
#     - "OR"
# - subtract_filter: A dictionary of conditions to subtract specific elements from the result.
# - subtract_filter_logic: Logical operator to combine multiple subtract filters. Options:
#     - "AND"
#     - "OR"

# ---------------------------
# Filter Key Usage Examples:
# ---------------------------

# Use filters to narrow down the included or subtracted elements. Examples:

# 1. Key-value pair:
#    - description: "Calculate area of internal walls"
#    - include_filter: PredefinedType: "INTERNAL"

# 2. Filter with multiple values:
#    - subtract_filter: Name: ["LUF", "Void"]

# 3. Filter with boolean value:
#    - subtract_filter: Pset_CoveringCommon.IsExternal: true

# 4. Filter with condition (operator, value):
#    - subtract_filter: Thickness: ("<", 0.1)

# Combine multiple conditions using include_filter_logic or subtract_filter_logic:
# Example:
#     include_filter: PredefinedType: "INTERNAL", Pset_SpaceCommon.IsExternal: true
#     include_filter_logic: "AND"

# adding new metrics and template:
# 1. add a new metric to the metrics list by copying this template:
# metrics:
#   new_metric:
#     description: "Description of the metric"
#     quantity_type: "area" or "volume" or "count"
#     ifc_entity: "IfcSpace"
#     pset_name: "Pset_Name" (leave blank for attributes)
#     prop_name: "Attribute Name or Property Name"
#     include_filter:
#       "Key": "Value"
#       "Key": ["Value1", "Value2"]
#       ...
#     include_filter_logic: "AND" or "OR"
#     subtract_filter:
#       "Key": ["<"", Number]
#       "Key": ["Value1", "Value2"]
#       ...
#     subtract_filter_logic: "OR"

# Explain the difference between metrics and room-based metrics:
# - metrics: Calculated based on all spaces or elements in the project.
# - room-based metrics: Calculated based on spaces grouped by room.

# TODO: include or exclude Filter merged to one, and with NOR added -> flatter hirachy
# TODO: . as seperator can lead to problems in Pset.Attribut
# TODO: use the IfcOpenshell logic for filtering => more felxibility and more stabel (https://docs.ifcopenshell.org/ifcopenshell-python/selector_syntax.html)

# Common column definitions for all metrics and benchmarks dataframe (dont delete the name "column_definitions")
column_definitions:
  metric_name:
    description: "Unique identifier for the metric"
    type: "string"
  value:
    description: "Calculated numeric value"
    type: "float"
  unit:
    description: "Unit of measurement (m², m³, ratio, etc.)"
    type: "string"
  category:
    description: "Type of measurement (area, volume, ratio, count)"
    type: "string"
  description:
    description: "Detailed explanation of what is being measured"
    type: "string"
  calculation_time:
    description: "When the metric was calculated"
    type: "datetime"
  status:
    description: "Calculation status (success/error)"
    type: "string"

metrics: #Dont delete the name "metrics". List all the standard metrics that return a single value for the entire project here
  gross_floor_area:
    description: "The gross floor area from the outside of the exterior walls, including all interior spaces, the area of spaces with Name = LUF is subtracted"
    quantity_type: "area"
    ifc_entity: "IfcSpace"
    pset_name: "Qto_SpaceBaseQuantities"
    prop_name: "NetFloorArea"
    include_filter:
      Name: "GrossArea"
    subtract_filter:
      Name: ["LUF", "Void", "Luftraum"]

  gross_volume:
    description: |
      The gross floor volume.
      In the abstractBIM IFC standard, Gross Volume is calculated based on
      the volume enclosed by the exterior face of exterior walls, including all interior spaces.
    quantity_type: "volume"
    ifc_entity: "IfcSpace"
    pset_name: "Qto_SpaceBaseQuantities"
    prop_name: "NetVolume"
    include_filter:
      Name: "GrossVolume"
    include_filter_logic: "AND"
    subtract_filter:
    subtract_filter_logic: "OR"

    # Space metrics
  space_interior_floor_area:
    description: "The total floor area of net interior spaces (between the walls and slabs), the area of spaces with Name = LUF or Void or Luftraum is subtracted"
    quantity_type: "area"
    ifc_entity: "IfcSpace"
    pset_name: "Qto_SpaceBaseQuantities"
    prop_name: "NetFloorArea"
    include_filter:
      PredefinedType: "INTERNAL"
    include_filter_logic: "AND"
    subtract_filter:
      Name: ["LUF", "Void", "Luftraum"]
    subtract_filter_logic: "OR"

  space_exterior_area:
    description: "The total area of exterior spaces (horizontal projection)"
    quantity_type: "area"
    ifc_entity: "IfcSpace"
    pset_name: "Qto_SpaceBaseQuantities"
    prop_name: "NetFloorArea"
    include_filter:
      PredefinedType: "EXTERNAL"
    include_filter_logic: "AND"

  space_interior_volume:
    description: "The total volume of net spaces (between the walls and slabs) interior spaces"
    quantity_type: "volume"
    ifc_entity: "IfcSpace"
    pset_name: "Qto_SpaceBaseQuantities"
    prop_name: "NetVolume"
    include_filter:
      PredefinedType: "INTERNAL"
    include_filter_logic: "OR"

  windows_exterior_area:
    description: "The total area of exterior windows"
    quantity_type: "area"
    ifc_entity: "IfcWindow"
    pset_name: "Qto_WindowBaseQuantities"
    prop_name: "Area"
    include_filter:
      Pset_WindowCommon.IsExternal: true
    include_filter_logic: "AND"

  windows_interior_area:
    description: "The total area of interior windows"
    quantity_type: "area"
    ifc_entity: "IfcWindow"
    pset_name: "Qto_WindowBaseQuantities"
    prop_name: "Area"
    include_filter:
      Pset_WindowCommon.IsExternal: false
    include_filter_logic: "AND"

  interior_walls_area:
    description: "The net side area of interior walls"
    quantity_type: "area"
    ifc_entity: "IfcWallStandardCase"
    pset_name: "Qto_WallBaseQuantities"
    prop_name: "NetSideArea"
    include_filter:
      Pset_WallCommon.IsExternal: false

  facade_vertical_area:
    description: "The total area of exterior coverings"
    quantity_type: "area"
    ifc_entity: "IfcCovering"
    pset_name: "Qto_CoveringBaseQuantities"
    prop_name: "NetArea"
    include_filter:
      PredefinedType: "CLADDING"
      Pset_CoveringCommon.IsExternal: true
    include_filter_logic: "AND"

  soffit_area:
    description: "The total area of soffits"
    quantity_type: "area"
    ifc_entity: "IfcCovering"
    pset_name: "Qto_CoveringBaseQuantities"
    prop_name: "NetArea"
    include_filter:
      PredefinedType: "INSULATION"
      Pset_CoveringCommon.IsExternal: true
    include_filter_logic: "AND"

  coverings_interior_area:
    description: "The total area of interior coverings"
    quantity_type: "area"
    ifc_entity: "IfcCovering"
    pset_name: "Qto_CoveringBaseQuantities"
    prop_name: "NetArea"
    include_filter:
      Pset_CoveringCommon.IsExternal: false
    include_filter_logic: "AND"

  slab_balcony_area:
    description: |
      The total area of balcony slabs.
      In the abstractBIM IFC standard, balcony slabs are defined as slabs with exterior space above.
      Note: Cantilevered roofs may also be included as they meet the same criteria.
    quantity_type: "area"
    ifc_entity: "IfcSlab"
    pset_name: "Qto_SlabBaseQuantities"
    prop_name: "NetArea"
    include_filter:
      Name: "Slab Balcony"
    include_filter_logic: "AND"

  slab_interior_area:
    description: "The total area of interior slabs"
    quantity_type: "area"
    ifc_entity: "IfcSlab"
    pset_name: "Qto_SlabBaseQuantities"
    prop_name: "NetArea"
    include_filter:
      PredefinedType: "FLOOR"
    include_filter_logic: "AND"

  roof_area:
    description: "The total area of roof slabs"
    quantity_type: "area"
    ifc_entity: "IfcSlab"
    pset_name: "Qto_SlabBaseQuantities"
    prop_name: "NetArea"
    include_filter:
      PredefinedType: "ROOF"
    include_filter_logic: "AND"

  base_slab_area:
    description: |
      The total area of base slabs.
      In the abstractBIM IFC standard, base slabs are defined as:
      - Base slabs: Slabs with an internal space above
      - Cantilevered Slabs: Also included as they meet the same criteria
      TODO: Add filter for spaces in contact with ground (manual data enrichment)
    quantity_type: "area"
    ifc_entity: "IfcSlab"
    pset_name: "Qto_SlabBaseQuantities"
    prop_name: "NetArea"
    include_filter:
      PredefinedType: "BASESLAB"
    include_filter_logic: "AND"

  doors_exterior_area:
    description: "The total area of exterior doors"
    quantity_type: "area"
    ifc_entity: "IfcDoor"
    pset_name: "Qto_DoorBaseQuantities"
    prop_name: "Area"
    include_filter:
      Pset_DoorCommon.IsExternal: true
    include_filter_logic: "AND"

  doors_interior_area:
    description: "The total area of interior doors"
    quantity_type: "area"
    ifc_entity: "IfcDoor"
    pset_name: "Qto_DoorBaseQuantities"
    prop_name: "Area"
    include_filter:
      Pset_DoorCommon.IsExternal: false
    include_filter_logic: "AND"

  # Walls metrics
  walls_exterior_net_side_area:
    description: "The total net side area of exterior walls (excluding openings)"
    quantity_type: "area"
    ifc_entity: "IfcWallStandardCase"
    pset_name: "Qto_WallBaseQuantities"
    prop_name: "NetSideArea"
    include_filter:
      Pset_WallCommon.IsExternal: true
    include_filter_logic: "AND"

  walls_interior_net_side_area:
    description: "The total net side area of interior walls (excluding openings)"
    quantity_type: "area"
    ifc_entity: "IfcWallStandardCase"
    pset_name: "Qto_WallBaseQuantities"
    prop_name: "NetSideArea"
    include_filter:
      Pset_WallCommon.IsExternal: false
    include_filter_logic: "AND"

  walls_interior_loadbearing_net_side_area:
    description: |
      The total area of interior structural walls.
      The default values are based on the abstractBIM IFC.
      Assumption is that walls thicker than 15cm are structural walls.
      This is a simplification and may not be 100% accurate.
    quantity_type: "area"
    ifc_entity: "IfcWallStandardCase"
    pset_name: "Qto_WallBaseQuantities"
    prop_name: "NetSideArea"
    include_filter:
      Pset_WallCommon.IsExternal: false
      Qto_WallBaseQuantities.Width: [">", 0.15]
    include_filter_logic: "AND"

  walls_interior_non_loadbearing_net_side_area:
    description: |
      The total area of internal non-load bearing walls
      The default values are based on the abstractBIM IFC.
      Assumption is that walls thinner than 15cm are non-load bearing walls.
      This is a simplification and may not be 100% accurate.
    quantity_type: "area"
    ifc_entity: "IfcWallStandardCase"
    pset_name: "Qto_WallBaseQuantities"
    prop_name: "NetSideArea"
    include_filter:
      Pset_WallCommon.IsExternal: false
      Qto_WallBaseQuantities.Width: ["<=", 0.15]  
    include_filter_logic: "AND"

  
    


# Room-based metrics
room_based_metrics: #Dont delete the name "room_based_metrics". List all the metrics calculated per room here e.g. window area by roomtyp
  windows_area_by_room:
    description: "Get windows grouped by room"
    ifc_entity: "IfcWindow"
    grouping_attribute: "GlobalId"
    pset_name: "Qto_WindowBaseQuantities"
    prop_name: "Area"

  doors_interior_area_by_room:  
    description: "Get interior doors grouped by room"
    ifc_entity: "IfcDoor"
    grouping_attribute: "GlobalId"
    pset_name: "Qto_DoorBaseQuantities"
    prop_name: "Area"
    include_filter:
      Pset_DoorCommon.IsExternal: false
    include_filter_logic: "AND"

  doors_exterior_area_by_room:
    description: "Get exterior doors grouped by room"
    ifc_entity: "IfcDoor"
    grouping_attribute: "GlobalId"
    pset_name: "Qto_DoorBaseQuantities"
    prop_name: "Area"
    include_filter:
      Pset_DoorCommon.IsExternal: true

  wall_surface_net_area_by_room:
    description: "Get wall coverings grouped by room"
    ifc_entity: "IfcCovering"
    grouping_attribute: "LongName"
    pset_name: "Qto_CoveringBaseQuantities"
    prop_name: "NetArea"
    include_filter:
      PredefinedType: "CLADDING"
      Pset_CoveringCommon.IsExternal: false
    include_filter_logic: "AND" 

derived_metrics:
  construction_area:
    description: "The total construction area. Relevance: Helps assess structural and usable footprint. Typical use: Estimating construction costs and comparing project scales."
    formula: "gross_floor_area - space_interior_floor_area"

  construction_volume:
    description: "The total construction volume. Relevance: Reflects the built volume above and below ground. Typical use: Energy demand modeling, material estimation."
    formula: "gross_volume - space_interior_volume"

  gv_to_gf_ratio:
    description: "Ratio of gross volume to gross floor area. Relevance: Indicates spatial efficiency and height characteristics. Typical use: Early-stage massing analysis and zoning checks."
    formula: "gross_volume / gross_floor_area"

  window_to_floor_ratio:
    description: "Ratio of window area to floor area. Relevance: Influences daylighting and thermal performance. Typical use: Energy simulations and facade design decisions."
    formula: "windows_exterior_area / gross_floor_area"

  facade_area_to_gross_volume_ratio:
    description: "Ratio of facade area to gross volume. Relevance: Indicates envelope efficiency. Typical use: Comparing compactness and evaluating surface-related energy loss."
    formula: "(facade_vertical_area + windows_exterior_area + doors_exterior_area) / gross_volume"

  facade_area_to_gross_floor_area_ratio:
    description: "Ratio of facade area to gross floor area. Relevance: Assesses building envelope exposure per usable area. Typical use: Thermal envelope design and cost estimation."
    formula: "(facade_vertical_area + windows_exterior_area + doors_exterior_area) / gross_floor_area"

  opening_area_to_total_facade_area_ratio:
    description: "Ratio of opening area to total facade area. Relevance: Key factor in daylight, ventilation, and heat loss. Typical use: Evaluating window-to-wall ratio for building code compliance."
    formula: "windows_exterior_area / facade_vertical_area"

  construction_area_to_gross_floor_area_ratio:
    description: "Ratio of construction area to gross floor area. Relevance: Measures structural overhead. Typical use: Analyzing design efficiency and structure-to-usage proportion."
    formula: "construction_area / gross_floor_area"

  construction_volume_to_gross_volume_ratio:
    description: "Ratio of construction volume to gross volume. Relevance: Indicates how much volume is occupied by structure vs. usable space. Typical use: Structural optimization and material estimation."
    formula: "construction_volume / gross_volume"

  total_envelope_area:
    description: "The total envelope area. Relevance: Indicates the total area of the building envelope. Typical use: Estimating construction costs and comparing project scales."
    formula: "facade_vertical_area + windows_exterior_area + doors_exterior_area + roof_area + soffit_area"

  total_envelope_area_to_gross_floor_area_ratio:
    description: "Ratio of total envelope area to gross floor area. Relevance: Indicates the total area of the building envelope per usable area. Typical use: Estimating construction costs and comparing project scales."
    formula: "total_envelope_area / gross_floor_area"

  total_envelope_area_to_gross_volume_ratio:
    description: "Ratio of total envelope area to gross volume. Relevance: Indicates the total area of the building envelope per usable volume. Typical use: Estimating construction costs and comparing project scales."
    formula: "total_envelope_area / gross_volume"





