name: Update Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc
          pip install ifcopenshell
          pip install pandas
          pip install pyyaml
          pip install -e .
          
      - name: Generate documentation
        run: |
          rm -rf docs/*
          # Generate docs without changing directory
          pdoc -o docs qto_buccaneer
          # Create index.html
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=qto_buccaneer.html">
              <script>window.location.href = "qto_buccaneer.html";</script>
            </head>
            <body>
              <p>Redirecting to documentation...</p>
            </body>
          </html>' > docs/index.html
          
      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "Update documentation" || echo "No changes to commit"
          git push 