name: Update Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the package with docs extras
          pip install -e .[docs]
          # Ensure pdoc3 is installed
          pip install pdoc3
          
      - name: Generate documentation
        run: |
          rm -rf docs/*
          pdoc --html --output-dir docs qto_buccaneer
          # Debug: List the contents of docs directory
          ls -R docs/
          # Create index.html with correct path
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=qto_buccaneer/index.html">
              <script>window.location.href = "qto_buccaneer/index.html";</script>
            </head>
            <body>
              <p>Redirecting to documentation...</p>
            </body>
          </html>' > docs/index.html
          
      # Add custom CSS for better formatting
      - name: Add custom styling
        run: |
          mkdir -p templates
          echo '
          /* Custom CSS */
          .docstring {
              padding: 1rem;
              margin: 1rem 0;
              background: #f8f9fa;
              border-radius: 4px;
          }
          
          .doc-contents {
              max-width: 900px;
              margin: 0 auto;
              padding: 2rem;
          }
          
          pre {
              background: #f1f1f1;
              padding: 1rem;
              border-radius: 4px;
              overflow-x: auto;
          }
          
          .signature {
              background: #e9ecef;
              padding: 1rem;
              margin: 1rem 0;
              border-radius: 4px;
          }' > templates/default.css
          
      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "Update documentation" || echo "No changes to commit"
          git push 