name: Update Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc
          pip install ifcopenshell
          pip install pandas
          pip install pyyaml
          pip install -e .
          
      - name: Prepare environment
        run: |
          # Create necessary directories
          mkdir -p src/qto_buccaneer/configs
          # Create a minimal config file for documentation generation
          echo "metrics:
            example_metric:
              description: Example metric
              quantity_type: area
              ifc_entity: IfcSpace" > src/qto_buccaneer/configs/metrics_config_abstractBIM.yaml
          
      - name: Generate documentation
        run: |
          rm -rf docs/*
          cd docs
          # Generate docs excluding problematic modules
          pdoc -o . ../src/qto_buccaneer --exclude validate_config_file
          # Create index.html
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=index.html">
              <script>window.location.href = "index.html";</script>
            </head>
            <body>
              <p>Redirecting to documentation...</p>
            </body>
          </html>' > index.html
          
      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "Update documentation" || echo "No changes to commit"
          git push 