name: Update Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc
          pip install ifcopenshell
          pip install pandas
          pip install pyyaml
          pip install -e .
          
      - name: Generate documentation with debug
        run: |
          echo "Current directory:"
          pwd
          echo "Python path:"
          python -c "import sys; print(sys.path)"
          echo "Installed packages:"
          pip list
          echo "Trying to import qto_buccaneer:"
          python -c "import qto_buccaneer; print('Import successful')"
          echo "Generating docs:"
          pdoc --html --output-dir docs --force qto_buccaneer --verbose
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs/
          git commit -m "Update documentation" || exit 0
          git push 