[theme]
primaryColor = "#FFC400"  # RGB(256,196,0)
backgroundColor = "#FFFFFF"  # White
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false 